name: 'Run tests and upload coverage'
description: 'Run tests and upload coverage'
inputs:
  NO_COVERAGE:
    description: 'set to a non-empty string to suppress gathering coverage'
    required: false
    default: ''
  GAP_TESTFILE:
    description: 'the file read by `run_tests.sh`'
    required: false
    default: '' # Default used by `run_tests.sh` is currently `tst/testall.g`
runs:
  using: "composite"
  steps:
      - name: "Run tests"
        run:  pkg-ci-scripts/run_tests.sh
        env:
          NO_COVERAGE: ${{ inputs.NO_COVERAGE }}
          GAP_TESTFILE: ${{ inputs.GAP_TESTFILE }}
        shell: bash
      - name: "Gather coverage"
        run:  pkg-ci-scripts/gather-coverage.sh
        env:
          NO_COVERAGE: ${{ inputs.NO_COVERAGE }}
        shell: bash
      - name: "Upload coverage data to codecov"
        run:  bash <(curl -s https://codecov.io/bash)
        shell: bash
